### ISSUE TITLE
how to deploy it on render.com

### ISSUE THREAD

**Issue by bugbounted** [Kunj-2206/VideoAI#1]
Hi [Kunj-2206](https://github.com/Kunj-2206),
please tell me how to deploy it on render.com
waiting for your response
finest regards

**Comment by Kunj-2206** [comment]
Hi @bugbounted.
This app has some serious bugs and security issues. So I recommend to not to deploy as a actual website. But if you want it for testing then in your server you can create django project and paste these files or you can update settings.py file in the Web_VideoAI folder. Moreover I will add more comments and proper indentation to enhance readability.
Hope you got your solution. 
Feel free to reach out for other issues.
